name: Tote
favicon: null
layout_spectrum: 0.8931003857869655
typography_spectrum: 0.6078163154888898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff213c'
    - '#d0131a'
    - '#ac110f'
    - '#c8211b'
    - '#e21f27'
  brandStrength: 0.9400130603462458
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
