name: Tote
favicon: null
layout_spectrum: 0.48566
typography_spectrum: 0.6078163154888898
title: Meta program
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001200'
    - '#eefeff'
    - '#426000'
    - '#5b78a0'
    - '#bcd4c3'
  brandStrength: 0.9400130603462458
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
