name: go-create
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: inspire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47c7d4'
    - '#fb7200'
    - '#fbfbfb'
    - '#fbee01'
    - '#8db900'
  brandStrength: 0.9400130603462458
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
